vcf_to_mask: /panfs/jay/groups/27/mccuem/dimml002/NuGEN/targets/nugen.Jan2024.NoMissingData.vcf.gz
vcf_to_mask_tbi: /panfs/jay/groups/27/mccuem/dimml002/NuGEN/targets/nugen.Jan2024.NoMissingData.vcf.gz.tbi
bcftools_directory: /panfs/jay/groups/27/mccuem/dimml002/micromamba/envs/impute/bin/bcftools
iterations: 1
mask_proportion: 0.8
reference_panel: /panfs/jay/groups/27/mccuem/dimml002/NuGEN/Imputation/reference_panel/beagle_54_all_breeds/isec/goldenPath.ref.vcf.gz 
reference_panel_tbi: /panfs/jay/groups/27/mccuem/dimml002/NuGEN/Imputation/reference_panel/beagle_54_all_breeds/isec/goldenPath.ref.vcf.gz.tbi 
breed: Averaged
breed_ab: SB
